# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                server_version: '%env(DATABASE_SERVER_VERSION)%'
                driver: pdo_mysql
                host: '%env(DATABASE_HOST)%'
                port: '%env(DATABASE_PORT)%'
                dbname: '%env(DATABASE_NAME)%'
                user: '%env(DATABASE_USER)%'
                password: '%env(DATABASE_PASSWORD)%'
                logging: false
                charset: UTF8
                mapping_types:
                    enum: string
                    # if using pdo_sqlite as your database driver:
                    #   1. add the path in parameters.yml
                    #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
                    #   2. Uncomment database_path in parameters.yml.dist
                    #   3. Uncomment next line:
                    #path: '%database_path%'
            reports:
                server_version: '%env(REPORTS_DATABASE_SERVER_VERSION)%'
                driver: pdo_mysql
                host: '%env(REPORTS_DATABASE_HOST)%'
                port: '%env(REPORTS_DATABASE_PORT)%'
                dbname: '%env(REPORTS_DATABASE_NAME)%'
                user: '%env(REPORTS_DATABASE_USER)%'
                password: '%env(REPORTS_DATABASE_PASSWORD)%'
                logging: false
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                auto_mapping: true
                connection: default
                mappings:
                    App:
                        dir: '%kernel.project_dir%/src/Entity'
                        is_bundle: false
                        type: annotation
                        prefix: 'App\Entity'
                        alias: App
                dql:
                    datetime_functions:
                        DATE: DoctrineExtensions\Query\Mysql\Date
                        STR_TO_DATE: DoctrineExtensions\Query\Mysql\StrToDate
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        YEAR: DoctrineExtensions\Query\Mysql\Year
            reports:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: reports
