<?php

namespace App\Repository;

/**
 * AccountsMergeFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountsMergeFormRepository extends \Doctrine\ORM\EntityRepository
{
}
