<?php

namespace App\Repository;

/**
 * AccountCloneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountCloneRepository extends \Doctrine\ORM\EntityRepository
{
}
