<?php

namespace App\Repository;

/**
 * ReportChartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportChartRepository extends \Doctrine\ORM\EntityRepository
{
}
