<?php

namespace App\Repository;

use App\Entity\Reports;

/**
 * ReportSummaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportSummaryRepository extends \Doctrine\ORM\EntityRepository
{


}
