<?php

namespace App\Repository;

/**
 * SharedFormSmsMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedFormSmsMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
