<?php

namespace App\Repository;

/**
 * SharedFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharedFormRepository extends \Doctrine\ORM\EntityRepository
{
}
